spring.application.name=inventoryservice
server.port=8082

# ============================
# POSTGRESQL - INVENTORY DB
# ============================

spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=postgres
spring.datasource.password=Sin0602

# ============================
# JPA
# ============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true